site_name: Veritrans - Java Client Documentation
use_directory_urls: false
theme_dir: 'custom'
pages:
- [index.md, Home]
- [javadoc/index.html, Javadoc]
- [sequence_diagram.md, Sequence Diagram]
- [sample_app.md, Sample App]
- [release_notes.md, Release Notes]